---
spring:
  h2:
    console:
      enabled: true     
      path: /h2-db
  datasource:
#    url: jdbc:h2:mem:supplierdb
    url: jdbc:h2:file:d:/supplierdb
#    username: sa
#    password: 
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
#      settings:
#        web-admin-password: admin